name: hangmangame

on:
  issues:
    types:
      - opened

jobs:
  update-hangman:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose your desired Python version
        
    - name: Run Hangman Script
      run: |
        python ./hangman.py ${{ github.event.issue.title }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config user.name "Your Name"
        git config user.email "your.email@example.com"
        git add README.md
        git commit -m "Update Hangman game state"
        git push
